color = input('enter the color:')
plural_noun= input('enter the plural_noun')
celebrity=input('enter a celebrity:')
print('roses are', color)
print('plural_noun', 'are blue')
print('I love', celebrity)
